apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: pgoweb
  labels:
    app: pgoweb
spec:
  type: NodePort
  ports:
  - port: 5000
    name: pgoweb
    targetPort: 5000
  selector:
    app: pgoweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgoweb
  name: pgoweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgoweb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: pgoweb
    spec:
      containers:
      - name: pgoweb
        image: ghcr.io/mawinkler/playground-one-web-app:main
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: pgo-credentials
